name: Build & Push Bookskyy Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: booksyyy
      VERSION: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:frontend-${VERSION} ./bookskyy

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:backend-${VERSION} ./backend

      - name: Push Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:frontend-${VERSION}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:backend-${VERSION}
